- name: variables
  hosts: localhost
  vars_files:
  - vars.yaml
  tasks: 
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, am learning {{course}} my self itsef from seeing {{source}} videos, I am practicing daily {{duration}}"