- name: variable preference 
  hosts: localhost
  vars:
    WISHES: Night11
  vars_files:
  - vars.yaml
  # vars_prompt:
  # - name: WISHES
  #   prompt: please enter your wishes
  #   private: false
  tasks: 
  - name: check preference
    vars:
     WISHES: Night15 
    ansible.builtin.debug:
      msg: "Hello, Good {{WISHES}}" 

# 1.Arguments
# 2.Prompt
# 3.