- name: check number
  hosts: localhost
  vars_prompt:
  - name: number 
    prompt: please enter number
    private: false

  tasks: 
  - name: number is lessthan 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is lessthan 10"
    when: number | int < 10

  - name: number is greaterthan 10
    ansible.builtin.debug:
      msg: "Given number {{number}} is greaterthan 10"
    when: number | int > 10