- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{person | default ('Charan')}}"


- name: upper case
  hosts: localhost
  vars:
    greeting: "Hello, good morning"
  tasks:
  - name: convert into upper case
    ansible.builtin.debug:
      msg: "{{greeting | upper}}"

- name: lower case
  hosts: localhost
  vars:
    greeting: "Hello, good morning"
  tasks:
  - name: convert into lower case
    ansible.builtin.debug:
      msg: "{{greeting | lower}}"

- name: remove duplicates
  hosts: localhost
  vars:
    numbers: [1, 2, 2, 4, 5, 4, 7, 8, 9, 8, 5, 4]
  tasks:
  - name: remove duplicates
    ansible.builtin.debug:
      msg: "Hello {{numbers | unique}}"

- name: min and max
  hosts: localhost
  vars:
    ages: [71, 62, 82, 24, 95, 54, 27, 18, 98, 58, 45, 74]
  tasks:
  - name: print min and max ages
    ansible.builtin.debug:
      msg: "min age: {{ages | min}}, max age: {{ages | max}}"

- name: convert dictinary into items/list
  hosts: localhost
  vars:
    my_dict:
      Course: Ansible
      Name: charan
      Time: 130min
  tasks:
  - name: print before convert dictinary into items/list
    ansible.builtin.debug:
      msg: " {{my_dict}}"

  - name: print after convert dictinary into items/list
    ansible.builtin.debug:
      msg: " {{my_dict | dict2items}}"
